/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
(function(){function r(){var a=[],c;for([c,d]of Object.entries(e.customcolors)){if("--shadow"===c){var b=d.replace("#","");var d=parseInt(b.substring(0,2),16);var l=parseInt(b.substring(2,4),16);b=parseInt(b.substring(4,6),16);d=`0 1px .5px rgba(${d}, ${l}, ${b}, .2)`}a.push(c+":"+d)}return":root{"+a.join(";")+"}"}var n=document.createElement("script");n.textContent="("+function(a,c){if(!window.efyt){window.efyt=!0;var b=JSON.parse(localStorage.getItem("enhancer-for-youtube"))||{};b.customcolors||
(b.customcolors={"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818","--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc","--shadow":"#000000"});b.customcssrules||(b.customcssrules="");b.theme||(b.theme="default-light");b.themevariant||(b.themevariant="youtube-deep-dark.css");if(0>b.theme.indexOf("default")){try{"custom"===b.theme?(b.customcssrules=b.customtheme,b.customtheme=!0,b.theme="youtube-deep-dark-custom"):/dark(.*)\.css/.test(b.theme)&&
(b.themevariant=b.theme,b.theme="youtube-deep-dark")}catch(v){}if("youtube-deep-dark"===b.theme){var d=a.createElement("link");d.id="efyt-theme-variables";d.rel="stylesheet";d.href=c+"/vendor/themes/"+b.themevariant}else if("youtube-deep-dark-custom"===b.theme){d=a.createElement("style");d.type="text/css";d.id="efyt-theme-variables";var l=[],p;for([p,f]of Object.entries(b.customcolors)){if("--shadow"===p){var g=f.replace("#","");var f=parseInt(g.substring(0,2),16);var t=parseInt(g.substring(2,4),
16);g=parseInt(g.substring(4,6),16);f=`0 1px .5px rgba(${f}, ${t}, ${g}, .2)`}l.push(p+":"+f)}d.textContent=":root{"+l.join(";")+"}"}var h=a.createElement("link");h.id="efyt-theme";h.rel="stylesheet";h.href=c+"/vendor/themes/youtube-deep-dark.material.css";a.head?(a.head.appendChild(d),a.head.appendChild(h)):a.documentElement.addEventListener("load",function q(u){a.head&&(a.documentElement.removeEventListener("load",q,!0),a.head.appendChild(d),a.head.appendChild(h))},!0)}if(b.customtheme){var k=a.createElement("style");
k.type="text/css";k.id="efyt-custom-theme";k.textContent=b.customcssrules;a.head?a.head.appendChild(k):a.documentElement.addEventListener("load",function q(u){a.head&&(a.documentElement.removeEventListener("load",q,!0),a.head.appendChild(k))},!0)}}}.toString()+')(document, "'+chrome.extension.getURL("resources")+'")';document.documentElement.appendChild(n);n.remove();var m=chrome.extension.getURL("resources"),e={customcolors:{"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818",
"--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc","--shadow":"#000000"},customcssrules:"",customtheme:!1,theme:"default-light",themevariant:"youtube-deep-dark.css"};chrome.storage.local.get(e,function(a){e=a});chrome.runtime.onMessage.addListener(function(a,c,b){if("preference-changed"===a.message)switch(c=a.value,a.name){case "customcolors":e.customcolors=c;if(a=document.head.querySelector("#efyt-theme-variables"))a.textContent=r();break;case "customcssrules":e.customcssrules=
c;if(a=document.head.querySelector("#efyt-custom-theme"))a.textContent=c,document.head.appendChild(a);break;case "customtheme":e.customtheme=c;a=document.head.querySelector("#efyt-custom-theme");c&&!a?(a=document.createElement("style"),a.type="text/css",a.id="efyt-custom-theme",a.textContent=e.customcssrules,document.head.appendChild(a)):!c&&a&&document.head.removeChild(a);break;case "theme":e.theme=c;a=document.head.querySelector("#efyt-theme-variables");b=document.head.querySelector("#efyt-theme");
"default-light"===c?(b&&document.head.removeChild(b),a&&document.head.removeChild(a),document.querySelectorAll("[dark]").forEach(function(d){d.removeAttribute("dark")})):"default-dark"===c?(b&&document.head.removeChild(b),a&&document.head.removeChild(a),document.documentElement.setAttribute("dark","")):"youtube-deep-dark"===c?(document.documentElement.setAttribute("dark",""),a&&!a.hasAttribute("href")&&(document.head.removeChild(a),a=!1),a||(a=document.createElement("link"),a.id="efyt-theme-variables",
a.rel="stylesheet",a.href=m+"/vendor/themes/"+e.themevariant,document.head.appendChild(a)),b||(b=document.createElement("link"),b.id="efyt-theme",b.rel="stylesheet",b.href=m+"/vendor/themes/youtube-deep-dark.material.css",document.head.appendChild(b)),e.customtheme&&(a=document.head.querySelector("#efyt-custom-theme"))&&document.head.appendChild(a)):"youtube-deep-dark-custom"===c&&(document.documentElement.setAttribute("dark",""),a&&a.hasAttribute("href")&&(document.head.removeChild(a),a=!1),a||(a=
document.createElement("style"),a.type="text/css",a.id="efyt-theme-variables",a.textContent=r(),document.head.appendChild(a)),b||(b=document.createElement("link"),b.id="efyt-theme",b.rel="stylesheet",b.href=m+"/vendor/themes/youtube-deep-dark.material.css",document.head.appendChild(b)),e.customtheme&&(a=document.head.querySelector("#efyt-custom-theme"))&&document.head.appendChild(a));break;case "themevariant":e.themevariant=c,(a=document.head.querySelector("#efyt-theme-variables"))&&a.hasAttribute("href")&&
(a.href=m+"/vendor/themes/"+c)}})})();