/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
(function(c){function g(){var b={};this.name?b[this.name]=this.value:b[this.id]=this.checked;chrome.storage.local.set(b)}function wa(){for(var b=[],d=0;d<r.length;d++)r[d].checked&&b.push(r[d].id);chrome.storage.local.set({controls:b})}function ia(){for(var b=c.querySelectorAll('#customcolors input[type="color"'),d={},e=0;e<b.length;e++)d[b[e].name]=b[e].value;chrome.storage.local.set({customcolors:d})}function ja(){fetch(`_locales/${p}/messages.json`).then(function(b){return b.json()}).then(function(b){A=
b.locale_dir.message;c.documentElement.lang=p.replace("_","-");c.body.dir=A;for(var d=v.length-1;0<=d;d--)v[d].textContent=b[v[d].dataset.text].message;for(d=q.length-1;0<=d;d--)q[d].dataset.tooltip=b[q[d].dataset.message].message;c.querySelector("#customcssrules").setAttribute("placeholder",b.custom_theme_instructions.message);c.querySelector("#customscript").setAttribute("placeholder",b.custom_script_instructions.message);chrome.storage.local.set({localecode:p,localedir:A})})}function I(){var b=
c.querySelector("#channels");b.textContent="";k.forEach(function(d){var e=c.createElement("bdi"),w=c.createElement("span"),t=c.createElementNS("http://www.w3.org/2000/svg","svg"),m=c.createElementNS("http://www.w3.org/2000/svg","path");w.textContent=d;e.appendChild(w);t.setAttributeNS(null,"version","1.1");t.setAttributeNS(null,"viewBox","0 0 24 24");m.setAttributeNS(null,"d","M0 0h24v24H0V0z");m.setAttributeNS(null,"fill","none");t.appendChild(m);m=c.createElementNS("http://www.w3.org/2000/svg",
"path");m.setAttributeNS(null,"d","M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm5 13.59L15.59 17 12 13.41 8.41 17 7 15.59 10.59 12 7 8.41 8.41 7 12 10.59 15.59 7 17 8.41 13.41 12 17 15.59z");t.appendChild(m);t.addEventListener("click",xa);e.appendChild(t);b.appendChild(e)})}function xa(){k.splice(k.indexOf(this.parentNode.textContent),1);chrome.storage.local.set({whitelist:k.toString()});I()}function ka(b){c.body.classList.add("overflow-hidden");B.style.display="block";b.style.display=
"block";b.scrollTop=0;B.classList.add("in");setTimeout(function(){c.body.classList.add("modal-open")},50)}function ya(b){c.body.classList.remove("modal-open");setTimeout(function(){b.style.display="none";B.classList.add("fade");B.classList.remove("in");setTimeout(function(){B.style.display="none";c.body.classList.remove("overflow-hidden")},300)},300)}var p=chrome.i18n.getMessage("locale_code"),A=chrome.i18n.getMessage("locale_dir"),v=c.querySelectorAll(".i18n"),B=c.querySelector("#modal-backdrop"),
q=c.querySelectorAll(".player-control .info"),r,k,x={blur:0,brightness:100,contrast:100,grayscale:0,huerotate:0,invert:0,saturate:100,sepia:0,applyvideofilters:!1,backgroundcolor:"#000000",backgroundopacity:85,blockads:!0,blockadsexceptforsubs:!1,blockautoplay:!0,blockhfrformats:!1,blockwebmformats:!1,cinemamode:!1,cinemamodewideplayer:!0,controls:"loop reverse-playlist volume-booster not-interested cinema-mode size pop-up-player speed video-filters screenshot keyboard-shortcuts options".split(" "),
controlspeed:!0,controlspeedmousebutton:!1,controlvolume:!1,controlvolumemousebutton:!1,customcolors:{"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818","--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc","--shadow":"#000000"},customcssrules:"",customscript:"",customtheme:!1,date:0,defaultvolume:!1,disableautoplay:!1,executescript:!1,expanddescription:!1,filter:"none",hidecardsendscreens:!1,hidechat:!1,hidecomments:!1,hiderelated:!1,
ignoreplaylists:!0,ignorepopupplayer:!0,localecode:p,localedir:A,message:!1,miniplayer:!0,miniplayerposition:"_top-left",miniplayersize:"_400x225",newestcomments:!1,overridespeeds:!0,pauseforegroundtab:!1,pausevideos:!0,popuplayersize:"640x360",qualityembeds:"medium",qualityembedsfullscreen:"hd1080",qualityplaylists:"hd720",qualityplaylistsfullscreen:"hd1080",qualityvideos:"hd720",qualityvideosfullscreen:"hd1080",reload:!1,reversemousewheeldirection:!1,selectquality:!1,selectqualityfullscreenoff:!1,
selectqualityfullscreenon:!1,speed:1,speedvariation:.1,stopvideos:!1,theatermode:!1,theme:"default-light",themevariant:"youtube-deep-dark.css",update:0,volume:50,volumemultiplier:3,volumevariation:5,whitelist:"",wideplayer:!1,wideplayerviewport:!1};chrome.storage.local.get(x,function(b){if(p===b.localecode){c.documentElement.lang=p.replace("_","-");c.body.dir=A;for(var d=v.length-1;0<=d;d--)v[d].textContent=chrome.i18n.getMessage(v[d].dataset.text);for(d=q.length-1;0<=d;d--)q[d].dataset.tooltip=chrome.i18n.getMessage(q[d].dataset.message);
c.querySelector("#customcssrules").setAttribute("placeholder",chrome.i18n.getMessage("custom_theme_instructions"));c.querySelector("#customscript").setAttribute("placeholder",chrome.i18n.getMessage("custom_script_instructions"))}else p=b.localecode,ja();c.querySelectorAll("nav a").forEach(function(a){a.addEventListener("focus",function(){this.parentNode.classList.add("focus")});a.addEventListener("blur",function(){this.parentNode.classList.remove("focus")})});c.querySelector("nav .donate a").addEventListener("click",
function(a){a.preventDefault();a=0>"bg cs da de el es et fi fr hr hu it lt lv nl pl pt_BR pt_PT ro sk sl sv".indexOf(chrome.i18n.getMessage("locale_code"))?"USD":"EUR";chrome.tabs.create({url:this.dataset.paypal.replace(/currency_code=[A-Z]+/,"currency_code="+a),active:!0})});d=c.querySelector("#locale");d.value=p;d.addEventListener("change",function(){p=this.value;ja()});d.addEventListener("focus",function(){this.parentNode.classList.add("focus")});d.addEventListener("blur",function(){this.parentNode.classList.remove("focus")});
"#cinemamode #cinemamodewideplayer #reversemousewheeldirection #hidecardsendscreens #hidecomments #hidechat #hiderelated #wideplayer #wideplayerviewport #applyvideofilters #blockhfrformats #blockwebmformats #expanddescription #newestcomments #executescript".split(" ").forEach(function(a){a=c.querySelector(a);a.checked=b[a.id];a.addEventListener("click",g)});c.querySelector("#keyboard-shortcuts-btn").addEventListener("click",function(){chrome.runtime.sendMessage({request:"configure-keyboard-shortcuts"})});
r=c.querySelectorAll('.player-control input[type="checkbox"]');for(d=0;d<r.length;d++)r[d].checked=-1<b.controls.indexOf(r[d].id)?!0:!1,r[d].addEventListener("click",wa);q=c.querySelectorAll(".player-control .info");for(d=q.length-1;0<=d;d--)q[d].addEventListener("click",function(a){a.preventDefault()});d=c.querySelector("#backgroundcolor");var e=c.querySelector("#backgroundopacity"),w=c.querySelector("#opacity"),t=c.querySelector("#cinemamode-background"),m=function(){var a=b.backgroundcolor.replace("#",
""),h=parseInt(a.substring(0,2),16),f=parseInt(a.substring(2,4),16);a=parseInt(a.substring(4,6),16);w.textContent=b.backgroundopacity+"%";t.style.backgroundColor=`rgba(${h}, ${f}, ${a}, ${b.backgroundopacity/100})`};d.value=b.backgroundcolor;d.addEventListener("input",function(){b.backgroundcolor=this.value;m();chrome.storage.local.set({backgroundcolor:this.value})});d.addEventListener("change",g);e.value=b.backgroundopacity;e.addEventListener("input",function(){b.backgroundopacity=Number(this.value);
m();chrome.storage.local.set({backgroundopacity:b.backgroundopacity})});m();var C=c.querySelector("#playback-speed"),D=c.querySelector("#custom-playback-speed");d=c.querySelector("#overridespeeds");var J=c.querySelector("#speedvariation");e=c.querySelector("#defaultvolume");var K=c.querySelector("#volume"),la=c.querySelector("#volume-preview"),y=c.querySelector("#volumemultiplier"),n=c.querySelector("#controlspeed"),L=c.querySelector("#controlspeedmousebutton"),ma=c.querySelector("#controlvolume"),
M=c.querySelector("#controlvolumemousebutton"),N=c.querySelector("#volumevariation"),na=c.querySelector("#miniplayer"),O=c.querySelector("#miniplayersize"),P=c.querySelector("#miniplayerposition");C.value=b.overridespeeds?1:b.speed;C.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});D.value=b.overridespeeds?b.speed:1;D.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});b.overridespeeds&&(C.classList.add("hidden"),
D.classList.remove("hidden"));d.checked=b.overridespeeds;d.addEventListener("click",function(){J.disabled=!this.checked;var a=c.querySelector("#playback-speed-label");a.classList.add("animated","blink");setTimeout(function(){a.classList.remove("animated","blink")},2400);C.classList.toggle("hidden");D.classList.toggle("hidden");chrome.storage.local.set({overridespeeds:this.checked,speed:parseFloat(this.checked?D.value:C.value)})});J.value=b.speedvariation;J.disabled=!b.overridespeeds;J.addEventListener("change",
function(){chrome.storage.local.set({speedvariation:parseFloat(this.value)})});n.checked=b.controlspeed;n.addEventListener("click",function(){L.disabled=!this.checked;chrome.storage.local.set({controlspeed:this.checked})});L.checked=b.controlspeedmousebutton;L.disabled=!b.controlspeed;L.addEventListener("click",g);e.checked=b.defaultvolume;e.addEventListener("click",function(){K.disabled=!this.checked;chrome.storage.local.set({defaultvolume:this.checked})});K.value=b.volume;K.disabled=!b.defaultvolume;
K.addEventListener("input",function(){b.volume=Number(this.value);la.textContent=b.volume;chrome.storage.local.set({volume:b.volume})});la.textContent=b.volume;y.value=b.volumemultiplier;y.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});ma.checked=b.controlvolume;ma.addEventListener("click",function(){M.disabled=!this.checked;N.disabled=!this.checked;chrome.storage.local.set({controlvolume:this.checked})});M.checked=b.controlvolumemousebutton;
M.disabled=!b.controlvolume;M.addEventListener("click",g);N.value=b.volumevariation;N.disabled=!b.controlvolume;N.addEventListener("change",function(){chrome.storage.local.set({volumevariation:Number(this.value)})});y.value=b.volumemultiplier;y.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});na.checked=b.miniplayer;na.addEventListener("click",function(){O.disabled=!this.checked;P.disabled=!this.checked;chrome.storage.local.set({miniplayer:this.checked})});
O.value=b.miniplayersize;O.disabled=!b.miniplayer;O.addEventListener("change",g);P.value=b.miniplayerposition;P.disabled=!b.miniplayer;P.addEventListener("change",g);d=c.querySelector("#blockads");var Q=c.querySelector("#blockadsexceptforsubs"),oa=c.querySelector("#whitelist-section"),aa=c.querySelector("#channel"),pa=c.querySelector("#whitelist-channel-btn");(d.checked=b.blockads)&&oa.classList.remove("hidden");d.addEventListener("click",function(){Q.disabled=!this.checked;oa.classList.toggle("hidden");
chrome.storage.local.set({blockads:this.checked})});Q.checked=b.blockadsexceptforsubs;Q.disabled=!b.blockads;Q.addEventListener("click",g);aa.addEventListener("keydown",function(a){13===a.keyCode&&pa.click()});k=""!==b.whitelist?b.whitelist.split(","):[];0<k.length&&I();pa.addEventListener("click",function(){var a=aa.value.replace(/,/g,"").trim();if(""!==a&&0>k.indexOf(a)){k.push(a);try{k.sort(function(h,f){return h.localeCompare(f)})}catch(h){k.sort()}chrome.storage.local.set({whitelist:k.toString()});
I()}aa.value=""});d=c.querySelector("#blockautoplay");var R=c.querySelector("#pauseforegroundtab"),S=c.querySelector("#ignoreplaylists"),T=c.querySelector("#stopvideos");d.checked=b.blockautoplay;d.addEventListener("click",function(){R.disabled=!this.checked;S.disabled=!this.checked;T.disabled=!this.checked;chrome.storage.local.set({blockautoplay:this.checked})});R.checked=b.pauseforegroundtab;R.disabled=!b.blockautoplay;R.addEventListener("click",g);S.checked=b.ignoreplaylists;S.disabled=!b.blockautoplay;
S.addEventListener("click",g);T.checked=b.stopvideos;T.disabled=!b.blockautoplay;T.addEventListener("click",g);d=c.querySelector("#pausevideos");var U=c.querySelector("#ignorepopupplayer");d.checked=b.pausevideos;d.addEventListener("click",function(){U.disabled=!this.checked;chrome.storage.local.set({pausevideos:this.checked})});U.checked=b.ignorepopupplayer;U.disabled=!b.pausevideos;U.addEventListener("click",g);d=c.querySelector("#disableautoplay");var qa=c.querySelector(".autoplay-toggle-button");
d.checked=b.disableautoplay;qa.setAttribute("aria-checked",!b.disableautoplay);d.addEventListener("click",function(){qa.setAttribute("aria-checked",!this.checked);chrome.storage.local.set({disableautoplay:this.checked})});var ba=c.querySelector("#selectquality"),u=c.querySelector("#selectqualityfullscreenon"),E=c.querySelector("#selectqualityfullscreenoff"),V=["#qualityvideos","#qualityplaylists","#qualityembeds"],W=["#qualityvideosfullscreen","#qualityplaylistsfullscreen","#qualityembedsfullscreen"];
ba.checked=b.selectquality;ba.addEventListener("click",function(){V.forEach(function(a){c.querySelector(a).disabled=!ba.checked});u.disabled=!this.checked;this.checked?(V.forEach(function(a){c.querySelector(a).disabled=!1}),u.disabled=!1,u.checked&&(W.forEach(function(a){c.querySelector(a).disabled=!1}),E.disabled=!1)):(V.forEach(function(a){c.querySelector(a).disabled=!0}),u.disabled=!0,W.forEach(function(a){c.querySelector(a).disabled=!0}),E.disabled=!0);chrome.storage.local.set({selectquality:this.checked})});
V.forEach(function(a){a=c.querySelector(a);a.value=b[a.id];a.disabled=!b.selectquality;a.addEventListener("change",g)});u.checked=b.selectqualityfullscreenon;u.addEventListener("click",function(){W.forEach(function(a){c.querySelector(a).disabled=!u.checked});E.disabled=!this.checked;chrome.storage.local.set({selectqualityfullscreenon:this.checked})});W.forEach(function(a){a=c.querySelector(a);a.value=b[a.id];a.disabled=!b.selectqualityfullscreenon;a.addEventListener("change",g)});E.checked=b.selectqualityfullscreenoff;
E.addEventListener("click",g);d=c.querySelector("#popuplayersize");d.value=b.popuplayersize;d.addEventListener("change",g);d=c.querySelector("#theatermode");d.checked=b.theatermode;d.addEventListener("click",function(){chrome.cookies.set({url:"https://www.youtube.com/watch",name:"wide",value:this.checked?"1":"0",domain:".youtube.com",path:"/",expirationDate:Math.floor(Date.now()/1E3)+31556926});chrome.storage.local.set({theatermode:this.checked})});n=c.querySelectorAll('input[name="theme"]');var X=
c.querySelector("#themevariant"),ca=c.querySelector("#customcolors");e=c.querySelector("#customtheme");var F=c.querySelector("#customcssrules");y=c.querySelector("#customcssrules-btn");var Y=c.querySelector("#customcssrules-checkmark");for(d=n.length-1;0<=d;d--)n[d].value===b.theme&&(n[d].checked=!0),n[d].addEventListener("click",g),n[d].addEventListener("click",function(){X.disabled="youtube-deep-dark"===this.value?!1:!0;ca.classList["youtube-deep-dark-custom"===this.value?"remove":"add"]("hidden")});
X.value=b.themevariant;X.disabled="youtube-deep-dark"===b.theme?!1:!0;X.addEventListener("change",g);ca.classList["youtube-deep-dark-custom"===b.theme?"remove":"add"]("hidden");var G=ca.querySelectorAll('input[type="color"');n=b.customcolors;for(d=G.length-1;0<=d;d--)G[d].value=n[G[d].name],G[d].addEventListener("change",ia);c.querySelector("#reset-custom-colors").addEventListener("click",function(){var a=x.customcolors;G.forEach(function(h){h.value=a[h.name]});ia()});e.checked=b.customtheme;e.addEventListener("click",
function(){F.parentNode.classList[this.checked?"remove":"add"]("hidden");chrome.storage.local.set({customtheme:this.checked})});F.value=b.customcssrules;F.parentNode.classList[b.customtheme?"remove":"add"]("hidden");F.addEventListener("focus",function(){Y.classList.remove("show")});y.addEventListener("click",function(){Y.classList.add("show");chrome.storage.local.set({customcssrules:F.value})});Y.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){Y.classList.remove("show")},
1200)});var da=c.querySelector("#customscript");d=c.querySelector("#customscript-btn");var Z=c.querySelector("#customscript-checkmark");da.value=b.customscript;da.addEventListener("focus",function(){Z.classList.remove("show")});d.addEventListener("click",function(){Z.classList.add("show");chrome.storage.local.set({customscript:da.value})});Z.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){Z.classList.remove("show")},1200)});d=c.querySelector("#export-modal-btn");
e=c.querySelector("#import-modal-btn");var l=c.querySelector("#backup-modal"),ra=l.querySelector(".close-modal"),sa=l.querySelector("#export-modal-content"),ta=l.querySelector("#export-textarea"),ua=l.querySelector("#import-modal-content"),ea=l.querySelector("#import-error"),va=l.querySelector("#import-textarea"),fa=l.querySelector("#import-btn"),ha=l.querySelector("#copy-to-clipboard-btn"),H=l.querySelector("#copy-to-clipboard-checkmark");d.addEventListener("click",function(){sa.classList.remove("hidden");
ha.classList.remove("hidden");H.classList.remove("hidden");ka(l);chrome.storage.local.get(null,function(a){var h={};h.version=chrome.runtime.getManifest().version;h.settings={};Object.keys(x).forEach(function(f){h.settings[f]="undefined"===typeof a[f]?x[f]:a[f]});ta.value=JSON.stringify(h)})});e.addEventListener("click",function(){ua.classList.remove("hidden");fa.classList.remove("hidden");ka(l)});ra.addEventListener("click",function(){ya(l);setTimeout(function(){sa.classList.add("hidden");ua.classList.add("hidden");
ea.classList.add("hidden");fa.classList.add("hidden");ha.classList.add("hidden");H.classList.add("hidden");va.value=""},600)});ha.addEventListener("click",function(a){ta.select();c.execCommand("copy");H.classList.add("show")});H.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){H.classList.remove("show")},1200)});fa.addEventListener("click",function(){var a=va.value.trim(),h={};if(""!==a){try{a=JSON.parse(a)}catch(z){ea.classList.remove("hidden");
return}if("object"===typeof a.settings){if(a.version&&/2\.0\.(9|10[0-1])/.test(a.version))try{a.settings.customcolors=x.customcolors;a.settings.customcssrules=a.settings.customtheme;a.settings.customtheme="custom"===a.settings.theme?!0:!1;"default"===a.settings.theme||"custom"===a.settings.theme?(a.settings.themevariant="youtube-deep-dark.css",a.settings.theme="default-light",chrome.runtime.sendMessage({request:"pref-cookie",obj:{theme:"light"}})):(a.settings.themevariant=a.settings.theme,a.settings.theme=
"youtube-deep-dark",chrome.runtime.sendMessage({request:"pref-cookie",obj:{theme:"dark"}}));var f=[];f.push("loop");f.push("reverse-playlist");0<=a.settings.toolbarbuttons.indexOf("boost")&&f.push("volume-booster");f.push("not-interested");0<=a.settings.toolbarbuttons.indexOf("cinema")&&f.push("cinema-mode");0<=a.settings.toolbarbuttons.indexOf("resize")&&f.push("size");f.push("pop-up-player");0<=a.settings.toolbarbuttons.indexOf("slowdown")&&f.push("speed-minus");f.push("speed");0<=a.settings.toolbarbuttons.indexOf("speedup")&&
f.push("speed-plus");f.push("video-filters");f.push("screenshot");f.push("keyboard-shortcuts");0<=a.settings.toolbarbuttons.indexOf("script")&&f.push("custom-script");0<=a.settings.toolbarbuttons.indexOf("options")&&f.push("options");a.settings.controls=f;a.settings.applyvideofilters=a.settings.enablefilters;a.settings.blockads=a.settings.removeads;a.settings.blockautoplay=a.settings.autopausevideos;a.settings.customscript=a.settings.script;a.settings.hidecardsendscreens=a.settings.removeannotations;
a.settings.miniplayer=a.settings.pinnedplayer;a.settings.miniplayerposition=a.settings.pinnedplayerposition;a.settings.miniplayersize=a.settings.pinnedplayersize;a.settings.qualityembeds=a.settings.quality2;a.settings.qualityembedsfullscreen=a.settings.quality1;a.settings.qualityplaylists=a.settings.quality1;a.settings.qualityplaylistsfullscreen=a.settings.quality1;a.settings.qualityvideos=a.settings.quality1;a.settings.qualityvideosfullscreen=a.settings.quality1;a.settings.stopvideos=a.settings.disablepreloading;
delete a.settings.autofocusevents;delete a.settings.autopausevideos;delete a.settings.disablepreloading;delete a.settings.enablefilters;delete a.settings.permissions;delete a.settings.pinnedplayer;delete a.settings.pinnedplayerposition;delete a.settings.pinnedplayersize;delete a.settings.quality1;delete a.settings.quality2;delete a.settings.quality3;delete a.settings.quality4;delete a.settings.removeads;delete a.settings.removeannotations;delete a.settings.script;delete a.settings.slideeffect;delete a.settings.toolbarbackgroundcolor;
delete a.settings.toolbarbordercolor;delete a.settings.toolbarbuttons;delete a.settings.toolbarcolor;delete a.settings.toolbarcoloractive;delete a.settings.toolbaropacity;delete a.settings.toolbartooltips;delete a.settings.transparency;delete a.settings.visitor_info1_live}catch(z){}Object.keys(a.settings).forEach(function(z){typeof x[z]===typeof a.settings[z]&&(h[z]=a.settings[z])});chrome.storage.local.clear(function(){chrome.runtime.lastError&&(c.documentElement.dataset.e=1);chrome.storage.local.set(h,
function(){window.scrollTo(0,0);c.location.reload()})})}else ea.classList.remove("hidden")}});c.addEventListener("keydown",function(a){27===a.keyCode&&ra.click()})});chrome.storage.onChanged.addListener(function(b,d){for(var e in b)if("undefined"!==typeof b[e].newValue)if("whitelist"===e&&b[e].newValue!==k.toString())k=""!==b[e].newValue?b[e].newValue.split(","):[],I();else if("theme"===e&&b[e].newValue!==c.querySelector('input[name="theme"]:checked').value)c.querySelector(`input[name="theme"][value="${b[e].newValue}"]`).checked=
!0;else if("customtheme"===e){d=c.querySelector("#customtheme");var w=c.querySelector("#customcssrules");d.checked!==b[e].newValue&&(d.checked=b[e].newValue,w.parentNode.classList[b[e].newValue?"remove":"add"]("hidden"))}})})(document);