/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
(function(){chrome.extension.inIncognitoContext&&chrome.storage.local.get({blockads:!0,blockadsexceptforsubs:!1,blockautoplay:!0,blockhfrformats:!1,blockwebmformats:!1,controlspeed:!0,controlspeedmousebutton:!1,controlvolume:!1,controlvolumemousebutton:!1,customcolors:{"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818","--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc","--shadow":"#000000"},customcssrules:"",customtheme:!1,
defaultvolume:!1,disableautoplay:!1,hidecardsendscreens:!1,hidechat:!1,hidecomments:!1,hiderelated:!1,ignoreplaylists:!0,ignorepopupplayer:!0,overridespeeds:!0,pauseforegroundtab:!1,pausevideos:!0,qualityembeds:"medium",qualityembedsfullscreen:"hd1080",qualityplaylists:"hd720",qualityvideos:"hd720",reversemousewheeldirection:!1,selectquality:!1,selectqualityfullscreenoff:!1,selectqualityfullscreenon:!1,speed:1,speedvariation:.1,stopvideos:!1,theme:"default-light",themevariant:"youtube-deep-dark.css",
volume:50,volumevariation:5,whitelist:""},function(l){var b=document.createElement("script");b.textContent="("+function(v){localStorage.setItem("enhancer-for-youtube",JSON.stringify(v));document.dispatchEvent(new Event("efyt-local-storage-changed"))}.toString()+")("+JSON.stringify(l)+")";document.head.appendChild(b);b.remove()});var A=document.createElement("script");A.textContent="("+function(l,b,v,w){if(!l.EnhancerForYouTube&&!l.efyt){function F(){a=JSON.parse(localStorage.getItem("enhancer-for-youtube"))||
{};"undefined"===typeof a.blockads&&(a.blockads=!0);"undefined"===typeof a.blockautoplay&&(a.blockautoplay=!0);"undefined"===typeof a.pausevideos&&(a.pausevideos=!0);"undefined"===typeof a.ignoreplaylists&&(a.ignoreplaylists=!0);a.customcolors||(a.customcolors={"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818","--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc","--shadow":"#000000"});a.customcssrules||(a.customcssrules="");a.theme||
(a.theme="default-light");a.themevariant||(a.themevariant="youtube-deep-dark.css");a.qualityvideos||(a.qualityvideos="hd720");a.qualityplaylists||(a.qualityplaylists="hd720");a.volume||(a.volume=50);a.whitelist||(a.whitelist="")}function G(){var c=Date.now(),f=c+2592E6;a.defaultvolume&&(localStorage["yt-player-volume"]=sessionStorage["yt-player-volume"]=JSON.stringify({data:JSON.stringify({volume:a.volume,muted:!1}),creation:c,expiration:f}));a.selectquality&&(localStorage["yt-player-quality"]=JSON.stringify({data:a[0<
location.href.indexOf("list=")?"qualityplaylists":"qualityvideos"],creation:c,expiration:f}));a.disableautoplay&&(localStorage["yt.autonav::autonav_disabled"]=JSON.stringify({data:!0,creation:c,expiration:f}))}function B(){C++;var c=b.querySelector("#c4-player");if(c)try{a.stopvideos?c.stopVideo():(c.playVideo(),c.pauseVideo(),c.querySelector(".ytp-spinner").style.display="none")}catch(f){}else 20>C&&(H=setTimeout(B,500))}function I(c){!m&&a.stopvideos&&1<=c&&3>=c&&n.stopVideo()}function x(c){m=!0;
b.removeEventListener("keydown",x,!0);b.removeEventListener("mousedown",y,!0)}function y(c){m=!0;b.removeEventListener("keydown",x,!0);b.removeEventListener("mousedown",y,!0)}var a,m,H,C,n;F();G();if("loading"===b.readyState&&(a.blockads||w)&&"/watch"===location.pathname){function c(f,d){if(d=f.args){var p=""!==a.whitelist?a.whitelist.split(","):[],k=!1,z="";if(d.raw_player_response&&"object"===typeof d.raw_player_response){var e=d.raw_player_response;try{-1!==p.indexOf(e.videoDetails.author)&&(k=
!0),z=e.playbackTracking.videostatsPlaybackUrl.baseUrl}catch(D){}k||a.blockadsexceptforsubs&&/subscribed=1/.test(z)||(delete e.playerAds,delete e.adPlacements)}else if(d.player_response&&"string"===typeof d.player_response){e=JSON.parse(d.player_response);try{-1!==p.indexOf(e.videoDetails.author)&&(k=!0)}catch(D){}!e||k||a.blockadsexceptforsubs&&/subscribed=1/.test(d.player_response)||(delete e.playerAds,delete e.adPlacements,d.player_response=JSON.stringify(e))}}return f}b.documentElement.addEventListener("load",
function p(d){l.yt&&yt.player&&yt.player.Application&&0<Object.keys(yt.player.Application).length&&(b.documentElement.removeEventListener("load",p,!0),yt.player.Application.create&&(yt.player.Application.create=function(k){return function(z,e,D){"object"===typeof e&&(e=c(e));return k.apply(this,arguments)}}(yt.player.Application.create)),yt.player.Application.createAlternate&&(yt.player.Application.createAlternate=function(k){return function(z,e,D){"object"===typeof e&&(e=c(e));return k.apply(this,
arguments)}}(yt.player.Application.createAlternate)))},!0)}if(0>a.theme.indexOf("default")){try{"custom"===a.theme?(a.customcssrules=a.customtheme,a.customtheme=!0,a.theme="youtube-deep-dark-custom"):/dark(.*)\.css/.test(a.theme)&&(a.themevariant=a.theme,a.theme="youtube-deep-dark")}catch(c){}if("youtube-deep-dark"===a.theme){var h=b.createElement("link");h.id="efyt-theme-variables";h.rel="stylesheet";h.href=v+"/vendor/themes/"+a.themevariant}else if("youtube-deep-dark-custom"===a.theme){h=b.createElement("style");
h.type="text/css";h.id="efyt-theme-variables";w=[];var E;for([E,q]of Object.entries(a.customcolors)){if("--shadow"===E){var r=q.replace("#","");var q=parseInt(r.substring(0,2),16);var J=parseInt(r.substring(2,4),16);r=parseInt(r.substring(4,6),16);q=`0 1px .5px rgba(${q}, ${J}, ${r}, .2)`}w.push(E+":"+q)}h.textContent=":root{"+w.join(";")+"}"}var t=b.createElement("link");t.id="efyt-theme";t.rel="stylesheet";t.href=v+"/vendor/themes/youtube-deep-dark.material.css";b.head?(b.head.appendChild(h),b.head.appendChild(t)):
b.documentElement.addEventListener("load",function d(f){b.head&&(b.documentElement.removeEventListener("load",d,!0),b.head.appendChild(h),b.head.appendChild(t))},!0)}if(a.customtheme){var g=b.createElement("style");g.type="text/css";g.id="efyt-custom-theme";g.textContent=a.customcssrules;b.head?b.head.appendChild(g):b.documentElement.addEventListener("load",function d(f){b.head&&(b.documentElement.removeEventListener("load",d,!0),b.head.appendChild(g))},!0)}if(a.hidechat||a.hidecomments||a.hiderelated)g=
b.createElement("style"),g.type="text/css",g.id="test",g.textContent="html.efyt-hide-chat ytd-live-chat-frame, html.efyt-hide-comments ytd-item-section-renderer.ytd-comments, html.efyt-hide-related ytd-watch-next-secondary-results-renderer, html.efyt-hide-related #related-skeleton.ytd-watch-flexy, html.efyt-hide-related .html5-video-player .html5-endscreen {display: none !important}",b.head?b.head.appendChild(g):b.documentElement.addEventListener("load",function d(f){b.head&&(b.documentElement.removeEventListener("load",
d,!0),b.head.appendChild(g))},!0),a.hidechat&&b.documentElement.classList.add("efyt-hide-chat"),a.hidecomments&&b.documentElement.classList.add("efyt-hide-comments"),a.hiderelated&&b.documentElement.classList.add("efyt-hide-related");var u="/watch"===location.pathname||/\/live$/.test(location.pathname)?"watch":/^\/(user|channel|c\/)/.test(location.pathname)?"channel":"browse";b.addEventListener("yt-navigate-start",function(c){"channel"===c.detail.pageType||"watch"===c.detail.pageType?(b.addEventListener("keydown",
x,!0),b.addEventListener("mousedown",y,!0),u=c.detail.pageType,m=!1):u=c.detail.pageType;clearTimeout(H)});b.addEventListener("yt-navigate-finish",function(c){"channel"===u&&(C=0,b.hidden?b.addEventListener("visibilitychange",function d(){b.removeEventListener("visibilitychange",d);setTimeout(B,1E3)}):setTimeout(B,1E3))});HTMLVideoElement.prototype.play=function(c){return function(){if(!m&&a.blockautoplay&&("watch"===u||"channel"===u||b.querySelector("ytd-app > ytd-miniplayer[active]"))&&(b.hidden||
a.pauseforegroundtab)&&(0>location.href.indexOf("list=")||!a.ignoreplaylists)&&this.classList.contains("html5-main-video"))n=this.parentNode.parentNode,a.pausevideos&&this.setAttribute("pausevideos",""),n.pauseVideo(),n.hasAttribute("onstatechange")||(n.setAttribute("onstatechange",""),n.addEventListener("onStateChange",I));else return c.apply(this,arguments)}}(HTMLVideoElement.prototype.play);l.MediaSource&&(MediaSource.isTypeSupported=function(c){return function(f){return a.blockhfrformats&&/framerate=([4-6]\d|\d{3,})/.test(f)||
a.blockwebmformats&&/video\/webm/.test(f)?!1:c(f)}}(MediaSource.isTypeSupported));b.addEventListener("keydown",x,!0);b.addEventListener("mousedown",y,!0);b.addEventListener("efyt-local-storage-changed",function(){F();G()});b.hidden||b.addEventListener("visibilitychange",function(){b.hidden&&(m=!0)},!0);b.addEventListener("DOMContentLoaded",function f(){b.removeEventListener("DOMContentLoaded",f);if(!l.Polymer&&0>a.theme.indexOf("default")){var d=b.head.querySelector("#efyt-theme-variables"),p=b.head.querySelector("#efyt-theme");
b.head.removeChild(p);b.head.removeChild(d)}})}}.toString()+')(window, document, "'+chrome.extension.getURL("resources")+'", '+chrome.extension.inIncognitoContext+")";document.documentElement.appendChild(A);A.remove()})();